=== jaeho222/2026-wanted/contracts/comments.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Comments (계약서 ① : collector → analyzer)",
  "description": "collector가 YouTube URL을 수집·전처리한 뒤 뱉는 정제된 댓글 리스트. analyzer는 이 형식만 입력으로 받는다.",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id", "text", "likes", "time"],
    "properties": {
      "id":    { "type": "string", "description": "댓글 고유 id (예: cmt_001)" },
      "text":  { "type": "string", "description": "정제된 댓글 본문" },
      "likes": { "type": "integer", "description": "좋아요 수" },
      "time":  { "type": "string", "format": "date-time", "description": "작성 시각 ISO8601" }
    }
  },
  "examples": [
    [
      { "id": "cmt_001", "text": "가격이 너무 올랐다", "likes": 1241, "time": "2026-01-10T12:00:00Z" },
      { "id": "cmt_002", "text": "환율 생각하면 이 정도는 납득됨", "likes": 532, "time": "2026-01-10T12:03:00Z" }
    ]
  ]
}

=== jaeho222/2026-wanted/comments.json
[
  {
    "id": "UgzDxcNKPYtm67d3vVB4AaABAg",
    "text": "이런 말 이상하지만 때묻지 않고 쪼없는 트로트 귀하다 귀해....",
    "likes": 0,
    "time": "2026-09-19T04:19:29Z"
  },
  {
    "id": "UgzlpsmUB5X7boW307Z4AaABAg",
    "text": "당황한 리마인은 즐추..",
    "likes": 0,
    "time": "2026-09-19T04:19:12Z"
  },
  {
    "id": "Ugw_mcWrCROJv9FvTu14AaABAg",
    "text": "빵 빵 미나미 봐봐 시골버스가 아니라 페라리여 ᄏᄏ 앞으로 튀어 나갈라 그래 ᄒᄒᄒ",
    "likes": 1,
    "time": "2026-09-19T04:19:10Z"
  },
  {
    "id": "Ugy-_lqnSaLe73sI7W94AaABAg",
    "text": "32년평생살면서 트로트 이렇게 많이들어본적 처음이다 진심..",
    "likes": 0,
    "time": "2026-09-19T04:19:00Z"
  },
  {
    "id": "UgwxbIVi634zw-OIFUV4AaABAg",
    "text": "잘한다 김제나😊",
    "likes": 1,
    "time": "2026-09-19T04:18:51Z"
  },
  {
    "id": "Ugwa-3GQexaEzvCEgRp4AaABAg",
    "text": "아니..나는 AI로 트로트 만드는 유튜브인줄알고 안봤는데 찐이었네",
    "likes": 1,
    "time": "2026-09-19T04:18:50Z"
  },
  {
    "id": "UgyAEEhl1VVKlR1IuQJ4AaABAg",
    "text": "1:51 ᄏᄏᄏᄏ 리브 오버액션 진짜 ᄏᄏᄏᄏᄏᄏᄏᄏ",
    "likes": 1,
    "time": "2026-09-19T04:18:45Z"
  },
  {
    "id": "UgyC9mj0SxPV66-frFF4AaABAg",
    "text": "떡이름이 뭐에요?",
    "likes": 0,
    "time": "2026-09-19T04:18:34Z"
  },
  {
    "id": "UgxsXDG6A8hTLa-wtTR4AaABAg",
    "text": "음원 활동은 안해되 정식 풀음원 나오면 좋겠네",
    "likes": 0,
    "time": "2026-09-19T04:18:18Z"
  },
  {
    "id": "UgxZjYNGXaFSYfPdDd54AaABAg",
    "text": "이젠 중장년에 노년층까지 섭렵하려는거냐 무섭다 리센느 어디까지 성장하려는거냐",
    "likes": 1,
    "time": "2026-09-19T04:18:06Z"
  },
  {
    "id": "UgxEBXyjqEQCif7VnZl4AaABAg",
    "text": "제나는 부케 유닛 활동 해도 되겠다 ᄏᄏᄏᄏᄏᄏᄏ 귀여운 신라 트롯 공주",
    "likes": 2,
    "time": "2026-09-19T04:17:57Z"
  },
  {
    "id": "UgwybCTdXpwAzouJ9XN4AaABAg",
    "text": "리브는 20세기말 테크노분위기(aka 이정현) 로 부탁한다",
    "likes": 1,
    "time": "2026-09-19T04:17:56Z"
  },
  {
    "id": "UgyZ8Lkln-4U1VHg4Bt4AaABAg",
    "text": "피디니무.. 편식이 어마어마하네... 제나만 보이는듯..",
    "likes": 0,
    "time": "2026-09-19T04:17:55Z"
  },
  {
    "id": "UgzApzvX2AVn87ze7l94AaABAg",
    "text": "18시간전 350만 화력 생각보다 약하네... 슈퍼스타 원이는 하루만에 500만 찍었는데 ᅲᅲᅲ 생각보다 사람들이 안보나 ᅮᅮᅮ",
    "likes": 0,
    "time": "2026-09-19T04:17:55Z"
  },
  {
    "id": "Ugx2OOppIfoFeCohd9l4AaABAg",
    "text": "와 요홍~두산하아~ 에서 게임 끝났네",
    "likes": 2,
    "time": "2026-09-19T04:17:50Z"
  },
  {
    "id": "Ugxu_aJ_FdD9cKfc5xR4AaABAg",
    "text": "이것도 다 들어주마ᄏᄏᄏ 너무 좋아 ᅮᅮ 트로트에 빠져버림ᄏᄏᄏ",
    "likes": 1,
    "time": "2026-09-19T04:17:42Z"
  },
  {
    "id": "Ugyd5H_kHDaORnMJ7M54AaABAg",
    "text": "대박🎉😂 너무 잘한네...코러스 죽이네❤",
    "likes": 1,
    "time": "2026-09-19T04:17:40Z"
  },
  {
    "id": "UgxTFTDxP6E2SMJEhf54AaABAg",
    "text": "나 트로트 좋아 했구나",
    "likes": 3,
    "time": "2026-09-19T04:16:54Z"
  },
  {
    "id": "UgynRInel_GuW6fET8V4AaABAg",
    "text": "Trot queen zena❤❤❤",
    "likes": 2,
    "time": "2026-09-19T04:16:52Z"
  },
  {
    "id": "UgxWz0lZo8fC6k7mppp4AaABAg",
    "text": "잘 한다❤❤❤❤❤",
    "likes": 1,
    "time": "2026-09-19T04:16:52Z"
  },
  {
    "id": "UgxbgSXavRTuS82Ses14AaABAg",
    "text": "미나미 빵빵댄스는 20년전 나이트 누님댄스인데...",
    "likes": 3,
    "time": "2026-09-19T04:16:52Z"
  },
  {
    "id": "UgzRFuxaUGGCw2NGaOV4AaABAg",
    "text": "아~떡 또 주문해야잖아",
    "likes": 2,
    "time": "2026-09-19T04:16:48Z"
  },
  {
    "id": "Ugz-AoTU9m1OoccQwL54AaABAg",
    "text": "트롯트 끊고 리센느 노래만 듣고 있는데 다시 트롯트로 돌아와야 되는건가~~ᄏ. 리센느 니들 때문에 루틴이 완전 깨져버리고 방콕하면서 리센느 영상만 보게되네요~ 리센는 니들 하늘 끝까지 날아 올라보자",
    "likes": 2,
    "time": "2026-09-19T04:16:40Z"
  },
  {
    "id": "UgyfazxkxdclLknq-XZ4AaABAg",
    "text": "진짜 돌잔치부터 초중고행사 - 군대- 직장인- 동문회 - 구순잔치까지도 커버 가능한 아이돌이다ᄏᄏᄏᄏᄏᄏᄏᄏᄏ",
    "likes": 6,
    "time": "2026-09-19T04:16:29Z"
  },
  {
    "id": "UgxLIWTK3c11j7A2FPp4AaABAg",
    "text": "나 트로트좋아하네",
    "likes": 2,
    "time": "2026-09-19T04:16:16Z"
  },
  {
    "id": "UgysdShQtowOToqxbEl4AaABAg",
    "text": "피디니무 잘한다잘한다 하니까 더잘하네",
    "likes": 4,
    "time": "2026-09-19T04:16:13Z"
  },
  {
    "id": "UgykK9fVOTv2rvai0lZ4AaABAg",
    "text": "진짜 제나 미치도록 귀엽다 이번편에서. 미쳤다 진짜ᄏᄏᄏᄏᄏᄏ",
    "likes": 3,
    "time": "2026-09-19T04:16:12Z"
  },
  {
    "id": "UgzoOPHWjF1Zbob3Vod4AaABAg",
    "text": "최고다",
    "likes": 2,
    "time": "2026-09-19T04:16:00Z"
  },
  {
    "id": "UgxPHELBSTUbUyIf-JF4AaABAg",
    "text": "미치겟다 ᄏᄏᄏᄏᄏᄏᄏ",
    "likes": 3,
    "time": "2026-09-19T04:15:44Z"
  },
  {
    "id": "UgwYWTlN3p34h9BB72N4AaABAg",
    "text": "시골 아줌마 할 때 원이 가리키는 ᄏᄏᄏᄏᄏ",
    "likes": 5,
    "time": "2026-09-19T04:15:41Z"
  },
  {
    "id": "UgwJe7Qn6zw8jEipyKN4AaABAg",
    "text": "제나의 맛깔난 목소리로 장윤정의 '어머나' 듣고 싶어요! 추석을 맞아 부모님께 맛있는 떡 선물해드리고 싶습니다!",
    "likes": 6,
    "time": "2026-09-19T04:15:18Z"
  },
  {
    "id": "Ugzg67qS3BxRc3IQB7h4AaABAg",
    "text": "안원잘부 채널 삭제하자 이제 솔직히 본업인 가수로써 대중들에게 당당하게 평가받자 더이상 컨텐츠뽑으려하지말고 노래연습 춤연습만 하는거다 그게 본업의 충실함이라고 생각한다 .",
    "likes": 2,
    "time": "2026-09-19T04:15:13Z"
  },
  {
    "id": "UgxkYru7v-P86eFNdZd4AaABAg",
    "text": "락 매니아인 내가 트로트를 듣고있다니",
    "likes": 2,
    "time": "2026-09-19T04:15:12Z"
  },
  {
    "id": "UgzDhEcs31SC1Y_DdBF4AaABAg",
    "text": "잘 한다~~❤❤",
    "likes": 1,
    "time": "2026-09-19T04:15:03Z"
  },
  {
    "id": "Ugwmw6WKIO0jJSL4Ned4AaABAg",
    "text": "다음엔 가인이어라를 가영으로 개사해서 불러보는 것도 웃길 거 같아요!!ᄏᄏᄏ 그리고 빵빵은 코러스 부분도 웃겨서 풀버전으로 보고 싶네요.. 떡도 부모님이 좋아하실 거 같아서 이벤트 참여할래용 고3인데 부모님께 효도(?) 좀 하고 싶어서...ᄒᄒ",
    "likes": 3,
    "time": "2026-09-19T04:15:03Z"
  },
  {
    "id": "UgzfAxf6qv0JXVKZsLJ4AaABAg",
    "text": "진짜 피디 감 미쳤고 르센느 기본기 쩔고 진짜 이친구들은 안뜰수가 없었네",
    "likes": 4,
    "time": "2026-09-19T04:15:02Z"
  },
  {
    "id": "UgzoZoAr3A7l8AGu_I54AaABAg",
    "text": "기엽다 진짜 ᄏᄏᄏᄏᄏᄏᄏ",
    "likes": 3,
    "time": "2026-09-19T04:14:44Z"
  },
  {
    "id": "UgyzQ62nh7pYSVXY86F4AaABAg",
    "text": "노후준비 완벽",
    "likes": 2,
    "time": "2026-09-19T04:14:39Z"
  },
  {
    "id": "Ugw9Qcho9EyfZv07c5l4AaABAg",
    "text": "와 어제 저녁에 35만일때 봤는데 벌써 350만이네",
    "likes": 3,
    "time": "2026-09-19T04:14:36Z"
  },
  {
    "id": "Ugysj-xMvL9RUk_kK2d4AaABAg",
    "text": "내 생에 서태지와아이들 이후로 이런 난리가 또 올줄이야...",
    "likes": 2,
    "time": "2026-09-19T04:14:31Z"
  },
  {
    "id": "UgxGZUbDrmpDnnG2gsB4AaABAg",
    "text": "우리 막둥이 잘한다~ 잘한다~",
    "likes": 4,
    "time": "2026-09-19T04:14:30Z"
  },
  {
    "id": "Ugx9kteZsOU3lN-0QC14AaABAg",
    "text": "2:36 헤이!! 가 너무 신나 ᄏᄏᄏᄏᄏᄏᄏ",
    "likes": 4,
    "time": "2026-09-19T04:14:30Z"
  },
  {
    "id": "UgxgFWf17KoraMGbYS54AaABAg",
    "text": "제나 노래잘부른다",
    "likes": 3,
    "time": "2026-09-19T04:14:25Z"
  },
  {
    "id": "UgyxcpB7P5xPfdcYLs94AaABAg",
    "text": "제나가 트로트의 감성을 아네",
    "likes": 3,
    "time": "2026-09-19T04:14:08Z"
  },
  {
    "id": "UgzwDixuyqtm5BjeQY54AaABAg",
    "text": "그래 이것도 사주마 32개 44000원 백년화편 밥알 찹쌀떡",
    "likes": 4,
    "time": "2026-09-19T04:14:06Z"
  },
  {
    "id": "UgzUAnixvaH-DX-U67J4AaABAg",
    "text": "아~~~니! 내는 원래 트로트를 조아해~!",
    "likes": 3,
    "time": "2026-09-19T04:14:05Z"
  },
  {
    "id": "Ugy0gq-09239KnXBAcl4AaABAg",
    "text": "진짜 국민 걸그룹이다 이정도면 아마도 역대급 걸그룹 탄생이다.",
    "likes": 4,
    "time": "2026-09-19T04:14:05Z"
  },
  {
    "id": "Ugz0pQDIw36-Gim3g6B4AaABAg",
    "text": "제나 이번건 너무 강력하다. 뭐 다른 멤버들이 어떻게 비벼 볼 수가 없겠네요. 이러다 트롯 가수로 전향 하는거 아닌가 몰라..",
    "likes": 7,
    "time": "2026-09-19T04:14:03Z"
  },
  {
    "id": "UgwTb98K6kd0ZoNnWrN4AaABAg",
    "text": "트 로트 한 소절 시작하자마자 로 맨틱한 매력에 심장이 두근두근 트 로트도 이렇게 잘 어울릴 줄이야 메 들리 내내 눈과 귀가 호강하고 들 을수록 자꾸만 빠져드는 까엉이 리 센느! 오래오래 보고싶다!",
    "likes": 5,
    "time": "2026-09-19T04:14:00Z"
  },
  {
    "id": "UgzW3cvTrDLa7qHKnI14AaABAg",
    "text": "우리 까엉이 최고! 벌써 몇번째 보고 있는 지, 몇 번을 더 보게 될 지 감도 안온다 리센느 애 들은 정말 팔색조 같은 매력을 가진 반짝반짝 빛나는 보석같은 친구들 같다",
    "likes": 3,
    "time": "2026-09-19T04:13:59Z"
  },
  {
    "id": "UgwpaScijvMlRxYSkEN4AaABAg",
    "text": "너무 당황스러워서 말도 안나옴 ᄏᄏᄏᄏᄏ",
    "likes": 2,
    "time": "2026-09-19T04:13:59Z"
  },
  {
    "id": "Ugw5ezvm_KXb68jjMNF4AaABAg",
    "text": "10:08 장~미의 이부분은 진짜 큰 감동",
    "likes": 1,
    "time": "2026-09-19T04:13:05Z"
  },
  {
    "id": "UgwZEW9tyNfY-1HecJ54AaABAg",
    "text": "이게 진짜 라구요? 니네 왜그러는건대 ᄏᄏ",
    "likes": 1,
    "time": "2026-09-19T04:13:05Z"
  },
  {
    "id": "UgwF_kPmyQF5HST6BIR4AaABAg",
    "text": "오라버니 도 함 뷸르쟈",
    "likes": 1,
    "time": "2026-09-19T04:13:02Z"
  },
  {
    "id": "UgwXS-tzjsIGYp7OY7F4AaABAg",
    "text": "벌써 조회수가 350만회 넘었네. 어느 누가 부르고 코러스를 해야 이 조회수가 나올까? 순수 국내체급으로 단시간에 이런 조회수와 4만개에 육박하는 댓글. 사랑해요 리센느 사랑한다 제나~~쏘리질럿~",
    "likes": 4,
    "time": "2026-09-19T04:12:53Z"
  },
  {
    "id": "UgyFWNExX9Y78wWNYXF4AaABAg",
    "text": "뒤에 네 명 코러스 거의 무표정인거 실화인가? ᄏᄏᄏ 제나 트로트 잘 부른다 ᄏᄏᄏᄏ",
    "likes": 3,
    "time": "2026-09-19T04:12:50Z"
  },
  {
    "id": "UgxTAzoht9aKwfb1aH94AaABAg",
    "text": "피디니무 천재야..... 리센느 버리지 말고 끝까지 책임지세용~~",
    "likes": 5,
    "time": "2026-09-19T04:12:47Z"
  },
  {
    "id": "Ugzsmjuc-kTGRJKaoD14AaABAg",
    "text": "안녕하신교 는 무슨종교인가요^^ 떡 구입해야겠다 ᄏᄏ",
    "likes": 6,
    "time": "2026-09-19T04:12:43Z"
  },
  {
    "id": "UgxzbF3xk_zhIPaFNfN4AaABAg",
    "text": "담에 트로트 제대로 한번 말아줘보소",
    "likes": 4,
    "time": "2026-09-19T04:12:27Z"
  },
  {
    "id": "UgxbMiOhk3dsTkNTLG14AaABAg",
    "text": "제나는 리센느가 못뜨고 있었다면 트롯 가수 됐겠네요^^ 용두산노래는 또 첨듣네요. 제나님 너무~~~너무~~~ 맛깔나게 부르네요",
    "likes": 11,
    "time": "2026-09-19T04:12:17Z"
  },
  {
    "id": "UgwTdnPGPrJiR707WJZ4AaABAg",
    "text": "까엉이 ❤️",
    "likes": 5,
    "time": "2026-09-19T04:12:12Z"
  },
  {
    "id": "UgxDtqRzA0UZkIWf9x94AaABAg",
    "text": "떡 주문했습니다. 맛나게 잘 먹겠습니다.",
    "likes": 4,
    "time": "2026-09-19T04:12:12Z"
  },
  {
    "id": "Ugx0A0348LiDMNghHUl4AaABAg",
    "text": "가요무대...추천합니다",
    "likes": 2,
    "time": "2026-09-19T04:12:11Z"
  },
  {
    "id": "UgzWQA9p9N7QkqNWxid4AaABAg",
    "text": "안원잘부에서 점점 옛날 무도의감성이ᄏᄏᄏ 뭘해도 재밌는데 다양하게하면서 캐릭터들도 다 잘 살아있어서 영상 1초1초 다 보게됨ᄏᄏ",
    "likes": 5,
    "time": "2026-09-19T04:12:06Z"
  },
  {
    "id": "UgyTSXCmgZB4aVlvNEp4AaABAg",
    "text": "거제 아저씨 선견지명 ᄃᄃ",
    "likes": 3,
    "time": "2026-09-19T04:12:02Z"
  },
  {
    "id": "UgxC3g3w886UmiE1Bml4AaABAg",
    "text": "까엉이 가요무대 한번 가자 ᄏᄏᄏᄏᄏᄏᄏᄏ",
    "likes": 3,
    "time": "2026-09-19T04:12:02Z"
  },
  {
    "id": "UgxSIvwSXL2ZJguehKt4AaABAg",
